/*
 *     (C) COPYRIGHT 1995-2000   Al von Ruff
 *         ALL RIGHTS RESERVED
 *
 *     The copyright notice above does not evidence any actual or
 *     intended publication of such source code.
 *
 */

static char sccsid[] = "@(#)ccinterv.c	1.4	05/01/98 SFdbase";

#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef SUNOS
#include <sys/unistd.h>
#else
#include <unistd.h>
#endif
#include "sfdbase.h"

extern int do_attribute(char *targetattr, attr_t *list, int options);

search_t        *title_list  = NULL;
extern object_t	*Objlist;
FILE		*notes_fp    = NULL;
FILE		*titles_fp   = NULL;
int		notes_offset = 0;


void
search_file(char *filename)
{
	object_t	*tmp;
	attr_t		*attr;
	extern int	line_number;

	line_number = 1;
	parse_pubs(filename);

	tmp = Objlist;
	while(tmp) {
		printf("%s|", tmp->ob_name);
		fprintf(titles_fp, "%s {\n", tmp->ob_name);
		do_attribute("TI", tmp->ob_attrs, NOOPTIONS);
		do_attribute("AE", tmp->ob_attrs, NOOPTIONS);
		do_attribute("YR", tmp->ob_attrs, DO_TITLES);
		do_attribute("IT", tmp->ob_attrs, DO_TITLES);
		do_attribute("PG", tmp->ob_attrs, NOOPTIONS);
		do_attribute("PB", tmp->ob_attrs, DO_TITLES);
		do_attribute("NT", tmp->ob_attrs, DO_NOTES);
		printf("\n");
		tmp = tmp->ob_next;
	}

	Objlist = NULL;
}


int
main(argc, argv)
	int	argc;
	char	*argv[];
{
	int		option;
	int		index;
	int		result;
	search_t	*tmp;
	char		path[256];
	struct stat	statbuf;
	FILE		*fp;

	close(1);
	fp = freopen(argv[1], "wb", stdout);

	strcpy(path, BASE);
	strcat(path, "/dbase.ascii");
	result = chdir(path);
        if (result != 0) {
                printf("CHDIR to %s failed\n", path);
                exit(1);
        }

	titles_fp = fopen("TITLES.INTERV", "wb+");
	fprintf(titles_fp, "## DO NOT EDIT!\n");
	fprintf(titles_fp, "## This file is autogenerated during the database build.\n");
	fprintf(titles_fp, "## Modify INTERVIEWS instead..\n");
	fprintf(titles_fp, "## \n");

	if ( stat("NOTES", &statbuf) == -1) {
		notes_fp = fopen("NOTES", "wb+");
	} else {
		notes_fp = fopen("NOTES", "rb+");
		notes_offset = statbuf.st_size;
		fseek(notes_fp, notes_offset, SEEK_SET);
	}

	search_file("INTERVIEWS");
	fclose(notes_fp);
	fclose(titles_fp);
}
